name: schedule_versions_ci

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * 1' #Run on Monday's 6am

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - uses: oleksiyrudenko/gha-git-credentials@v1
        with:
          token: '${{ secrets.GITHUB_TOKEN }}'

      - name: Refresh versions
        run: ./gradlew refreshVersions

      - name: Create branch and checkout if don't exist
        run: |
          echo "========= branch"
          git branch ci_refresh_versions
          echo "========= checkout"
          git checkout ci_refresh_versions
          echo "========= add"
          git add -A
          echo "========= commit"
          git commit --allow-empty -m "[CI]: Add new versions if exist"
          echo "========= push"
          git push -u origin ci_refresh_versions
          echo "========= diff"
          git diff origin/main origin/ci_refresh_versions

      - name: Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          branch: ci_refresh_versions
          base: main
          title: '[CI] Refresh Version'
          reviewers: Canato
          labels: Merge When Ready