name: schedule_versions_ci

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * 1' #Run on Monday's 6am

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Refresh versions
        run: ./gradlew refreshVersions

      - name: Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: CI - Add new versions if exist
          delete-branch: true
          branch: ci/refresh_versions
          base: main
          title: '[CI] Refresh Version'
          reviewers: Canato
          labels: Merge When Ready